repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: 'README.md'
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: dart-format
        name: Dart Format
        entry: dart format .
        language: system
        pass_filenames: false
        exclude: |
          ^(build/|ios/|android/|.dart_tool/)

      - id: dart-fix
        name: Dart Fix
        entry: dart fix --apply
        language: system
        pass_filenames: false
        exclude: |
          ^(build/|ios/|android/|.dart_tool/)

      - id: dart-analyze
        name: Dart Analyze
        entry: dart analyze
        language: system
        pass_filenames: false
        exclude: |
          ^(build/|ios/|android/|.dart_tool/)
