// country_utils.dart

/// A map of ISO 3166-1 alpha-2 country codes to country names
const Map<String, String> countryCodeMap = {
  'AF': 'Afghanistan',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AD': 'Andorra',
  'AO': 'Angola',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BD': 'Bangladesh',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BJ': 'Benin',
  'BO': 'Bolivia',
  'BA': 'Bosnia and Herzegovina',
  'BR': 'Brazil',
  'BG': 'Bulgaria',
  'CA': 'Canada',
  'CN': 'China',
  'CO': 'Colombia',
  'HR': 'Croatia',
  'CU': 'Cuba',
  'CZ': 'Czech Republic',
  'DK': 'Denmark',
  'EG': 'Egypt',
  'EE': 'Estonia',
  'FI': 'Finland',
  'FR': 'France',
  'DE': 'Germany',
  'GR': 'Greece',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'IN': 'India',
  'ID': 'Indonesia',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IT': 'Italy',
  'JP': 'Japan',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KR': 'South Korea',
  'KW': 'Kuwait',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LY': 'Libya',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MY': 'Malaysia',
  'MX': 'Mexico',
  'MA': 'Morocco',
  'NP': 'Nepal',
  'NL': 'Netherlands',
  'NZ': 'New Zealand',
  'NG': 'Nigeria',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PL': 'Poland',
  'PT': 'Portugal',
  'QA': 'Qatar',
  'RO': 'Romania',
  'RU': 'Russia',
  'SA': 'Saudi Arabia',
  'RS': 'Serbia',
  'SG': 'Singapore',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'ZA': 'South Africa',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'SY': 'Syria',
  'TH': 'Thailand',
  'TR': 'Turkey',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates',
  'GB': 'United Kingdom',
  'US': 'United States',
  'UZ': 'Uzbekistan',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'YE': 'Yemen',
  'ZW': 'Zimbabwe',
  // Add more if needed
};

/// Returns the country name for a given ISO country [code]
String getCountryName(String? code) {
  if (code == null || code.isEmpty) return code!;
  return countryCodeMap[code.toUpperCase()] ?? code;
}
